# Generated by Django 5.2.1 on 2025-05-26 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('sc', 'Single Choice'), ('mc', 'Multiple Choice'), ('tx', 'Text'), ('scal', 'echelle (1-5)')], max_length=4)),
                ('required', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='sondages.question')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True, null=True)),
                ('choix', models.ManyToManyField(blank=True, to='sondages.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondages.question')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sondages.reponse')),
            ],
        ),
        migrations.CreateModel(
            name='Sondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(default='Poppins', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reponse',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondages.sondage'),
        ),
        migrations.AddField(
            model_name='question',
            name='sondage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sondages.sondage'),
        ),
    ]
