# Generated by Django 5.2.1 on 2025-05-26 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reponse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sondage',
            name='limit_ip',
            field=models.BooleanField(default=True),
        ),
    ]
