# Generated by Django 5.2.1 on 2025-05-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLanguagePreference',
        ),
    ]
